spring.application.name=immobilier-backend

server.port=8080

# ===============================
# MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.jwt.secret=change-this-secret-key-before-production-change-this-secret-key
app.jwt.expiration=86400000